export const START_LOAD_LIBRARY = 'START_LOAD_LIBRARY';
export const LOAD_LIBRARY_SUCCESS = 'LOAD_LIBRARY_SUCCESS';
export const SHOW_ADD_BUTTONS = 'SHOW_ADD_BUTTONS';
export const HIDE_ADD_BUTTONS = 'HIDE_ADD_BUTTONS';
